<?php

/**
 * Implements hook_node_info()
 */
function friend_node_info() {
    return array(
        'friend' => array(
            'name' => t('Friend'),
            'base' => 'friend',
            'description' => t('New Friend'),
            'has_title' => TRUE,
            'title_label' => t('Friend')
         )
    );
}

/**
 * Implement hook_form()
 */
function friend_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

/**
 * Implements hook_theme().
 */

function friend_theme($existing, $type, $theme, $path) {
    $theme = array();
    $theme['node__friend'] = array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--friend',
      'path' => drupal_get_path('module', 'friend') . '/templates',
     );
    return $theme;
  }

  